steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  dir: auto-regist
  entrypoint: gcloud
  args:
  - functions
  - deploy
  - auto-regist
  - --gen2
  - --region=${_REGION}
substitutions:
  _REGION: us-central1
